In [3]:
import numpy as np
import time

In [5]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [9]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorized version: " + str(1000*(toc-tic)) + " ms")

249501.1175432661
vectorized version: 0.9388923645019531 ms


In [11]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]

toc = time.time()
print(c)
print("For Loop Version: " + str(1000*(toc-tic)) + " ms")

249501.1175432633
For Loop Version: 240.00787734985352 ms


In [12]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0], [1.2, 104.0, 52.0, 8.0], [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [26]:
# axis = 0 sums vertically
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [27]:
percentage = 100 * (A / cal.reshape(1,4))
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])